# Generated by Django 4.1.3 on 2022-11-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commentaires_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
